.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "TITAN" "1" "December 2017" "" ""
.
.SH "NAME"
\fBTitan\fR \- Advanced CS:GO report and commend bot
.
.SH "SYNOPSIS"
\fBtitan\fR [\fIargs\fR\.\.\.]
.
.br
\fBtitan\fR \fBreport\fR \fB\-t\fR \fItarget\fR \fBm\fR \fImatch id\fR\.\.\.
.
.br
\fBtitan\fR \fBcommend\fR
.
.br
.
.SH "DESCRIPTION"
\fBTitan\fR is an advanced Counter\-Strike Global Offensive report and commendation bot\. Its goal is to maintain a clean Matchmaking system by sending a target forcefully (by 11 reports) into Overwatch\. It provides a advanced set of features and high effiency when compared against other report and commendation bots\.
.
.P
In its default mode, \fBTitan\fR opens up a user\-friendly clickable UI that can be used for reporting and commending aswell as adding multiple new bot accounts to Titans internal list\.
.
.SH "OPTIONS"
These options control whether \fBTitan\fR should start using the UI or directly begin reporting / commending\.
.
.TP
\fBreport\fR
Instructs \fBTitan\fR to automatically start reporting the provided target in a match provided by the Match ID\.
.
.TP
\fBcommand\fR
Instructs \fBTitan\fR to automatically start commending the provided target\.
.
.P
Verb arguments control what should happen and only work when with a provided verb (\fBreport\fR and \fBcommend\fR)\.
.
.TP
\fB\-t\fR, \fB\-\-target\fR
Required\. Provides the target that should be reported or commended by \fBTitan\fR\. Works for both \fBreport\fR and \fBcommend\fR\.
.
.TP
\fB\-m\fR, \fB\-\-match\fR
Optional\. Provides the Match ID in which a target should be reported in by \fBTitan\fR\. Only works with \fBreport\fR verb\.
.
.TP
\fB\-i\fR, \fB\-\-index\fR
Optional\. Provides the \fBaccounts\.json\fR index which instructs what accounts should be used for reporting / commending by \fBTitan\fR\. Works for both \fBreport\fR and \fBcommend\fR\.
.
.P
These options control the reporting options\. These only work with the \fBreport\fR verb\.
.
.TP
\fB\-\-abusivetext\fR
Optional\. If passed, the target will be reported for Abuse Text Chat\.
.
.TP
\fB\-\-abusivevoice\fR
Optional\. If passed, the target will be reported for Abuse Voice Chat\.
.
.TP
\fB\-\-griefing\fR
Optional\. If passed, the target will be reported for Griefing\.
.
.TP
\fB\-\-aimhacking\fR
Optional\. If passed, the target will be reported for Aim Hacking\.
.
.TP
\fB\-\-wallhacking\fR
Optional\. If passed, the target will be reported for Wall Hacking\.
.
.TP
\fB\-\-otherhacking\fR
Optional\. If passed, the target will be reported for Other Hacking\.
.
.P
These options control the commending options\. These only work with the \fBcommend\fR verb\.
.
.TP
\fB\-\-leader\fR
Optional\. If passed, the target will be commended for being a leader\.
.
.TP
\fB\-\-friendly\fR
Optional\. If passed, the target will be commended for being friendly\.
.
.TP
\fB\-\-teacher\fR
Optional\. If passed, the target will be commended for being a teacher\.
.
.P
These option control the behaviour of \fBTitan\fR\.
.
.TP
\fB\-f\fR, \fB\-\-file\fR
Optional\. Provides path to \fBaccounts\.json\fR in which the bot accounts that are used by \fBTitan\fR for reporting and commending are listed\.
.
.TP
\fB\-s\fR, \fB\-\-secure\fR
Optional\. If passed, console output will be secured so that no account information or other serious information will be printed\. This can be used for taking screenshots or recording videos\.
.
.TP
\fB\-b\fR, \fB\-\-noblacklist\fR
Optional\. Disables the internal \fBTitan\fR blacklist that prevents people botting the owner and friends of this report and commend bot\.
.
.SH "ENVIRONMENT"
.
.TP
\fBTITAN_WEB_API_KEY\fR
If exists, \fBTitan\fR will prefer to use the Steam Web API key provided with that environment variable\. If it is not set and the user inputted a Steam Web API key within \fBTitan\fR, it will be saved to this environment variable\.
.
.SH "BUGS"
Bugs within \fBTitan\fR can be reported on GitHub: https://github\.com/Marc3842h/Titan
.
.SH "COPYRIGHT"
\fBTitan\fR is licensed under the MIT license\. Copyright (C) 2017 Marc3842h
.
.SH "SEE ALSO"
steam(6), mono(1)
