#!/usr/bin/env bash

# Quick and dirty hack to change permissions from root to our own
owner=$(stat -c '%U' /opt/Titan/Titan.exe)

if [ "$owner" != "$USER" ]; then
    sudo chown -R "$USER" "/opt/Titan"
fi

TERM=xterm mono /opt/Titan/Titan.exe
